### ISSUE TITLE
add controller support

### ISSUE THREAD

**Issue by Android986player** [GMH-Code/Qwasm2#4]

**Comment by GMH-Code** [comment]
By controller do you mean:

1. On-screen touch controls, or:
2. Physical gamepad support?

**Comment by GMH-Code** [comment]
Regarding the physical gamepad support, this was implemented but wasn't working, so I've fixed it.

If you meant on-screen touch controls, please let me know.

**Comment by Android986player** [comment]
thanks just physical usb gamepad support 4 both quakes

**Comment by GMH-Code** [comment]
Could you verify that your controller now works with Quake 2?

After starting the game in your browser, you'll need to press one of the controller buttons to activate it.  Doing so will cause the in-game console to output some text.  The analogue sticks should then 'just work' to strafe, walk and look, but you will need to bind the buttons to the functionality you want, using the standard controls menu.

Activating the controller will also enable a hidden menu option allowing you to tweak sensitivity of the analogue sticks, but those usually don't need changing.

Quake 1 may be more of a pain to add this functionality to, but I have some ideas on how to deal with that.

**Comment by GMH-Code** [comment]
Closing as completed since I've not heard from you and I believe the functionality for this project is now there.

I've not had any other requests for the Quake engine, but I will consider joystick functionality there if enough people talk to/ask me about it.
